update compile script to add libde265, libheif, and libwebp

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -12,32 +12,89 @@ VENDOR_DIR="$BUILD_DIR/vendor"
 INSTALL_DIR="$VENDOR_DIR/imagemagick"
 IMAGE_MAGICK_VERSION="${IMAGE_MAGICK_VERSION:-7.1.1-17}"
 CACHE_FILE="$CACHE_DIR/imagemagick-$IMAGE_MAGICK_VERSION.tar.gz"
+LIB_DE265_VERSION="${LIB_DE265_VERSION:-1.0.12}"
+LIB_HEIF_VERSION="${LIB_HEIF_VERSION:-1.16.2}"
+LIB_WEBP_VERSION="${LIB_WEBP_VERSION:-1.3.2}"
 
-if [ ! -f $CACHE_FILE ]; then
-  # install imagemagick
-  IMAGE_MAGICK_FILE="ImageMagick-$IMAGE_MAGICK_VERSION.tar.xz"
-  IMAGE_MAGICK_DIR="ImageMagick-$IMAGE_MAGICK_VERSION"
-  IMAGE_MAGICK_URL="https://download.imagemagick.org/archive/releases/$IMAGE_MAGICK_FILE"
+# build lib version base-url configure-options
+build() {
+  PRODUCT="$1"
+  PRODUCT_VERSION="$2"
+  PRODUCT_DIR="$PRODUCT-$PRODUCT_VERSION"
+  PRODUCT_FILE="$PRODUCT_DIR.tar.gz"
+  PRODUCT_URL="$3/$PRODUCT_FILE"
+  CONFIGURE_ARGS="$4"
+  CMAKE_ARGS="$5"
 
-  echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
-  wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
+  echo "-----> Downloading $PRODUCT from $PRODUCT_URL"
+  curl -L $PRODUCT_URL -o $BUILD_DIR/$PRODUCT_FILE | indent
 
-  echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
-  if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
-    echo "Error: Unable to download ImageMagick" | indent
+  echo "-----> Extracting $PRODUCT from $BUILD_DIR/$PRODUCT_FILE"
+  if [ ! -f $BUILD_DIR/$PRODUCT_FILE ]; then
+    echo "Error: Unable to download $PRODUCT" | indent
     ls $BUILD_DIR | indent
     exit 1;
   fi
-  tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE | indent
+  tar xvf $BUILD_DIR/$PRODUCT_FILE | indent
 
-  echo "-----> Building ImageMagick"
-  cd $IMAGE_MAGICK_DIR
+  echo "-----> Building $PRODUCT"
+  cd $PRODUCT_DIR
   export CPPFLAGS="-I$INSTALL_DIR/include"
   export LDFLAGS="-L$INSTALL_DIR/lib"
-  ./configure --prefix=$INSTALL_DIR
-  make && make install
+  export PKG_CONFIG_PATH="$INSTALL_DIR/lib/pkgconfig"
+
+  # build via cmake
+  if [ "$CMAKE_ARGS" != "" ]; then
+    mkdir build
+    cd build
+    if cmake -DCMAKE_PREFIX_PATH=$INSTALL_DIR -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR $CMAKE_ARGS; then
+      echo "cmake configure successful"
+    else
+      echo "Error: cmake configure failed"
+      exit 1;
+    fi
+  fi
+
+  # configure
+  if [ -f ./configure ]; then
+    if ./configure --prefix=$INSTALL_DIR $CONFIGURE_ARGS; then
+      echo "configure successful"
+    else
+      echo "Error: ./configure failed"
+      exit 1;
+    fi
+  fi
+
+  # install in custom prefix
+  if make && make install; then
+    echo "make && make install successful"
+  else
+    echo "Error: make && make install failed"
+    exit 1;
+  fi
+
+  # exit and remove src/build dir
+  if [ "$CMAKE_ARGS" != "" ]; then
+    cd ..
+  fi
   cd ..
-  rm -rf $IMAGE_MAGICK_DIR
+  rm -rf $PRODUCT_DIR
+}
+
+if [ ! -f $CACHE_FILE ]; then
+  build "libde265" "${LIB_DE265_VERSION}" "https://github.com/strukturag/libde265/releases/download/v${LIB_DE265_VERSION}" \
+        "--disable-dec265 --disable-sherlock265" ".."
+  build "libheif" "${LIB_HEIF_VERSION}" "https://github.com/strukturag/libheif/releases/download/v${LIB_HEIF_VERSION}" \
+        "" "-DWITH_EXAMPLES=OFF --preset=release-noplugins .."
+  build "libwebp" "${LIB_WEBP_VERSION}" "https://storage.googleapis.com/downloads.webmproject.org/releases/webp"
+  build "ImageMagick" $IMAGE_MAGICK_VERSION "https://download.imagemagick.org/archive/releases" \
+        "--with-webp --with-tiff --with-png --with-heic"
+
+  # cleanup lib files
+  cd $INSTALL_DIR
+  find . -type f \( -name "*.a" -or -name "*.la" \) -delete
+  rm -rf lib/pkgconfig
+  rm -rf lib/cmake
 
   # cache for future deploys
   echo "-----> Caching ImageMagick installation"
@@ -59,7 +116,6 @@ else
 fi
 
 echo "-----> Writing policy file"
-mkdir -p $INSTALL_DIR/etc/ImageMagick
 cat > $INSTALL_DIR/policy.xml <<EOF
 <policymap>
   <policy domain="coder" rights="none" pattern="EPHEMERAL" />
@@ -67,14 +123,6 @@ cat > $INSTALL_DIR/policy.xml <<EOF
   <policy domain="coder" rights="none" pattern="MVG" />
   <policy domain="coder" rights="none" pattern="MSL" />
 </policymap>
-EOF
-
-echo "-----> Writing config file"
-cat > $INSTALL_DIR/magic.xml <<EOF
-<magicmap>
- <magic name="JPEG" offset="0" target="\377\330\377"/> 
- <magic name="PNG" offset="0" target="\211PNG\r\n\032\n"/> 
-</magicmap>
 EOF
 
 # update PATH and LD_LIBRARY_PATH
